[project]
name = "isynclinux"
version = "0.2.1"
description = "Sync your iCloud files to a linux directory"
readme = "README.md"
requires-python = ">=3.11"
dependencies = ["click==8.3.1", "pyicloud==2.3.0", "rich==14.3.2"]

[project.scripts]
isynclinux = "isynclinux.syncer:cli"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
