[project]
name = "isynclinux"
version = "0.1.0"
description = "Sync your iCloud files to a linux directory"
readme = "README.md"
requires-python = ">=3.8"
dependencies = ["click==8.1.3", "pyicloud==1.0.0"]

[project.scripts]
isynclinux = "isynclinux.syncer:main"
